title: Jiajian, XIAO
url: "https://jiajian-xiao.github.io"
#baseurl: "/researcher"

markdown: kramdown
remote_theme: ankitsultana/researcher@gem
tracking_id: G-YELYJJLFMZ

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About Me"
   link: "/"
 - name: "Resume"
   link: "Resume_Jiajian.pdf"
 - name: "Contact"
   link: "contact"
